repos:
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        name: detect-secrets-scan
        args: ['--baseline', '.secrets.baseline']
        exclude: poetry.lock
    -   id: detect-secrets
        name: detect-secrets-audit
        args: ['audit', '.secrets.baseline']

repos:
- repo: https://github.com/semgrep/semgrep
  rev: 'v1.79.0'
  hooks:
    - id: semgrep
      args: ['--config', 'p/r2c-security-audit', '--error', '--skip-unknown-extensions']
