name: Secret Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    detect-secrets:
        name: Secret Scanning
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12.4

            - name: Install detect-secrets
              run: pip install detect-secrets

            - name: Scan for secrets
              run: detect-secrets scan --baseline .secrets.baseline --exclude-files poetry.lock

            - name: Audit secrets
              run: detect-secrets audit .secrets.baseline
